### ISSUE TITLE
Test event-scanner's run function and others

### ISSUE THREAD

**Issue by TimDaub** [leapdao/challenge-services#10]
## Scope

- Some functions in the event-scanner haven't been properly tested so far. The main one, the `run` function e.g. needs some tests

## Deliverables

- Test remaining functions to up code coverage

## Gain for the project

- Verified correctness of the service

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
bounty timed out
