### ISSUE TITLE
Implement a failover mechanism

### ISSUE THREAD

**Issue by TimDaub** [leapdao/challenge-services#2]
## Scope

- challenge-services run on Docker and docker-compose currently
- A crontab is configured to perform an action every X minutes
- There's a scenario where the service fails
- In this case, we'd like to deploy a new instance of the service quickly to catch up with the blocks that have been produced on the main chain

## Delivery

- Investigate if AWS ECS, docker-compose or Kubernetes provide a way to define failover scenarios
- Implement failover mechanism
- Deploy and demonstrate a service that handles a failover as expected

## Gain for the project

- Ability to challenge invalid exits and dark periods

## Roles

bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
bounty timed out
